// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"
)

type LoginAttempt struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Success   bool         `json:"success"`
	LoginTime sql.NullTime `json:"login_time"`
}

type User struct {
	Email     string         `json:"email"`
	CreatedBy sql.NullString `json:"created_by"`
	Passhash  string         `json:"passhash"`
	IsActive  bool           `json:"is_active"`
	IsAdmin   bool           `json:"is_admin"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	LastLogin sql.NullTime   `json:"last_login"`
}

type UserChange struct {
	ID        int32          `json:"id"`
	Email     string         `json:"email"`
	UpdatedBy sql.NullString `json:"updated_by"`
	Pwd       sql.NullBool   `json:"pwd"`
	IsActive  sql.NullBool   `json:"is_active"`
	IsAdmin   sql.NullBool   `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type UserDeletion struct {
	ID        int32          `json:"id"`
	Email     string         `json:"email"`
	DeletedBy sql.NullString `json:"deleted_by"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
