// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, email string) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeleteUser(ctx context.Context, email string) error
	GetChanges(ctx context.Context, arg GetChangesParams) ([]*UserChange, error)
	GetChangesCount(ctx context.Context) (int64, error)
	GetChangesCountForUser(ctx context.Context, email string) (int64, error)
	GetChangesEarliestFirst(ctx context.Context, arg GetChangesEarliestFirstParams) ([]*UserChange, error)
	GetChangesForUser(ctx context.Context, arg GetChangesForUserParams) ([]*UserChange, error)
	GetChangesForUserEarliestFirst(ctx context.Context, arg GetChangesForUserEarliestFirstParams) ([]*UserChange, error)
	GetDeletions(ctx context.Context, arg GetDeletionsParams) ([]*UserDeletion, error)
	GetDeletionsCount(ctx context.Context) (int64, error)
	GetFailedLoginAttemptsForUser(ctx context.Context, arg GetFailedLoginAttemptsForUserParams) ([]*LoginAttempt, error)
	GetLoginAttemptsForUser(ctx context.Context, arg GetLoginAttemptsForUserParams) ([]*LoginAttempt, error)
	GetPasswordForUser(ctx context.Context, email string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error)
	GetUserCount(ctx context.Context) (int64, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*ListUsersRow, error)
	ListUsersDescending(ctx context.Context, arg ListUsersDescendingParams) ([]*ListUsersDescendingRow, error)
	RegisterLoginAttempt(ctx context.Context, arg RegisterLoginAttemptParams) error
	UpdateUserAttributes(ctx context.Context, arg UpdateUserAttributesParams) (*UpdateUserAttributesRow, error)
}

var _ Querier = (*Queries)(nil)
